[main]
term=foot
font=JetBrainsMono Nerd Font:size=11.25
initial-window-size-chars = 110x32
pad = 6x6
include=~/.config/foot/onedark
# include=/usr/share/foot/themes/moonfly

[scrollback]
lines=10000
indicator-position=relative
indicator-format=line

[mouse]
hide-when-typing=yes

[cursor]
style=beam
blink=no

[key-bindings]
clipboard-copy=Control+Shift+c
clipboard-paste=Control+Shift+v

[csd]
size=0
border-width=1
border-color=ff404040



