general.live_config_reload = true

[window]
dimensions = { columns = 110, lines = 32 }
padding = { x = 6, y = 6 }
title = "Alacritty"
dynamic_title = true
resize_increments = true
# opacity = 0.6
# blur = true
# decorations = "None"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }
size = 11.25

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true

# [terminal]
# osc52 = "OnlyCopy"

[[keyboard.bindings]]
key = "Plus"
mods = "Control"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "Minus"
mods = "Control"
action = "DecreaseFontSize"

[[keyboard.bindings]]
key = "Key0"
mods = "Control"
action = "ResetFontSize"

[[keyboard.bindings]]
key = "U"
mods = "Control|Shift"
action = "ScrollPageUp"

[[keyboard.bindings]]
key = "D"
mods = "Control|Shift"
action = "ScrollPageDown"

# Vague for Alacritty

[colors]
cursor = { text = "#141415", cursor = "#cdcdcd" }

[colors.primary]
background = '#141415'
foreground = '#cdcdcd'

[colors.normal]
black = '#252530'
red = '#d8647e'
green = '#7fa563'
yellow = '#f3be7c'
blue = '#6e94b2'
magenta = '#bb9dbd'
cyan = '#aeaed1'
white = '#cdcdcd'

[colors.bright]
black = '#606079'
red = '#e08398'
green = '#99b782'
yellow = '#f5cb96'
blue = '#8ba9c1'
magenta = '#c9b1ca'
cyan = '#bebeda'
white = '#d7d7d7'

[colors.hints.start]
foreground = "CellBackground"
background = "CellForeground"

[colors.hints.end]
foreground = "CellBackground"
background = "CellForeground"

[colors.search.matches]
foreground = "CellBackground"
background = "CellForeground"

[colors.search.focused_match]
foreground = "CellBackground"
background = '#f3be7c'

# Upstream: https://github.com/vague-theme/vague-alacritty/blob/main/vague.toml
