#!/bin/bash

execute_bootstrap() {
  hold_packages
  install_packages
  install_extras
  remove_packages
  stow_dotfiles
  apply_gsettings
  load_keybindings
  fix_qt5ct
  # install_old_font
}

add_repos() {
  local repo_file="add-repository"
  sudo apt-add-repository $(<"$repo_file")
}

hold_packages() {
  sudo apt-mark hold fonts-ubuntu fonts-ubuntu-console vlc
}

install_packages() {
  local pkg_file="apt-install"
  sudo apt update && sudo apt install -y $(<"$pkg_file")
}

remove_packages() {
  local rm_file="apt-remove"
  sudo apt remove -y $(<"$rm_file")
  sudo apt autoremove -y
}

stow_dotfiles() {
  (cd $HOME/Stash/dotfiles && stow *)
}

apply_gsettings() {
  echo "Applying gsettings..."
  ./gsettings
}

load_keybindings() {
  local kb_file="keybindings"
  echo "Loading keybindings..."
  dconf load /org/cinnamon/desktop/keybindings/ < "$kb_file"
}

fix_qt5ct() {
  echo "Fixing qt5ct..."
  echo "export QT_QPA_PLATFORMTHEME=qt5ct" >> $HOME/.profile
}

install_brave() {
  sudo curl -fsSLo /usr/share/keyrings/brave-browser-archive-keyring.gpg https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
  sudo curl -fsSLo /etc/apt/sources.list.d/brave-browser-release.sources https://brave-browser-apt-release.s3.brave.com/brave-browser.sources
  sudo apt update && sudo apt install brave-browser
}

install_old_font() {
  local deb_path="fonts-ubuntu_0.83-6ubuntu1_all.deb"
    echo "Installing font..."
    sudo dpkg -i "$deb_path"
}

execute_bootstrap
# reboot

